import type { Property, PropertyImage } from "@/types/property";

// Helper to create demo images from picsum.photos (consistent via seed)
function demoImages(propertyId: string, seeds: number[]): PropertyImage[] {
  return seeds.map((seed, i) => ({
    id: `img-${propertyId}-${i}`,
    property_id: propertyId,
    url: `https://picsum.photos/seed/${seed}/800/500`,
    alt_text: null,
    sort_order: i,
    is_primary: i === 0,
    created_at: "",
  }));
}

// Sample properties — will be replaced by Supabase queries
export const sampleProperties: Property[] = [
  {
    id: "p1",
    city_id: "noida",
    area_id: "sector-150",
    title: "3BHK Premium Flat in ATS Pristine",
    slug: "3bhk-ats-pristine-sector-150",
    description: "Spacious 3BHK apartment in one of Sector 150's most premium societies. East-facing, fully furnished with modular kitchen. Walking distance to Botanical Garden metro.",
    property_type: "flat",
    transaction_type: "sell",
    status: "active",
    price: 9500000,
    price_per_sqft: 6800,
    area_sqft: 1400,
    bedrooms: 3,
    bathrooms: 2,
    floor_number: 12,
    total_floors: 25,
    facing: "East",
    year_built: 2019,
    rera_id: "UPRERAPRJ1234",
    is_featured: true,
    latitude: 28.5678,
    longitude: 77.3901,
    address: "ATS Pristine, Sector 150, Noida",
    amenities: ["Swimming Pool", "Gym", "Club House", "Power Backup", "24x7 Security", "Parking"],
    ai_analysis: null,
    nearby_places: null,
    view_count: 245,
    inquiry_count: 18,
    possession_date: "2019-06-01",
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
    city: { id: "noida", name: "Noida", slug: "noida", state: "Uttar Pradesh", description: null, latitude: 28.5355, longitude: 77.3910, meta: null, created_at: "" },
    area: { id: "sector-150", city_id: "noida", name: "Sector 150", slug: "sector-150", latitude: 28.5678, longitude: 77.3901, description: null, meta: null, created_at: "" },
    images: demoImages("p1", [101, 102, 103, 104, 105]),
  },
  {
    id: "p2",
    city_id: "noida",
    area_id: "gaur-city",
    title: "2BHK Ready to Move in Gaur City",
    slug: "2bhk-gaur-city-greater-noida-west",
    description: "Well-maintained 2BHK in Gaur City 2. South-facing with balcony. Close to schools, hospital, and market. Ideal for families and first-time buyers.",
    property_type: "flat",
    transaction_type: "sell",
    status: "active",
    price: 4200000,
    price_per_sqft: 4200,
    area_sqft: 1000,
    bedrooms: 2,
    bathrooms: 2,
    floor_number: 7,
    total_floors: 18,
    facing: "South",
    year_built: 2017,
    rera_id: "UPRERAPRJ5678",
    is_featured: false,
    latitude: 28.5900,
    longitude: 77.4300,
    address: "Gaur City 2, Greater Noida West",
    amenities: ["Gym", "Park", "Power Backup", "Security", "Parking"],
    ai_analysis: null,
    nearby_places: null,
    view_count: 189,
    inquiry_count: 12,
    possession_date: "2017-12-01",
    created_at: "2024-02-10T00:00:00Z",
    updated_at: "2024-02-10T00:00:00Z",
    city: { id: "noida", name: "Greater Noida West", slug: "noida", state: "Uttar Pradesh", description: null, latitude: 28.5900, longitude: 77.4300, meta: null, created_at: "" },
    area: { id: "gaur-city", city_id: "noida", name: "Gaur City", slug: "gaur-city", latitude: 28.5900, longitude: 77.4300, description: null, meta: null, created_at: "" },
    images: demoImages("p2", [201]),
  },
  {
    id: "p3",
    city_id: "noida",
    area_id: "sector-1",
    title: "3BHK in Ace Divino with Club Membership",
    slug: "3bhk-ace-divino-sector-1",
    description: "Premium 3BHK in Ace Divino, Sector 1 Greater Noida West. Comes with club membership, reserved parking, and modular kitchen. RERA registered.",
    property_type: "flat",
    transaction_type: "sell",
    status: "active",
    price: 6500000,
    price_per_sqft: 5200,
    area_sqft: 1250,
    bedrooms: 3,
    bathrooms: 2,
    floor_number: 15,
    total_floors: 22,
    facing: "North-East",
    year_built: 2020,
    rera_id: "UPRERAPRJ9012",
    is_featured: true,
    latitude: 28.5850,
    longitude: 77.4250,
    address: "Ace Divino, Sector 1, Greater Noida West",
    amenities: ["Swimming Pool", "Gym", "Club House", "Tennis Court", "Power Backup", "24x7 Security", "CCTV", "Parking"],
    ai_analysis: null,
    nearby_places: null,
    view_count: 312,
    inquiry_count: 24,
    possession_date: "2020-03-01",
    created_at: "2024-03-05T00:00:00Z",
    updated_at: "2024-03-05T00:00:00Z",
    city: { id: "noida", name: "Greater Noida West", slug: "noida", state: "Uttar Pradesh", description: null, latitude: 28.5850, longitude: 77.4250, meta: null, created_at: "" },
    area: { id: "sector-1", city_id: "noida", name: "Sector 1", slug: "sector-1", latitude: 28.5850, longitude: 77.4250, description: null, meta: null, created_at: "" },
    images: demoImages("p3", [301, 302, 303]),
  },
  {
    id: "p4",
    city_id: "noida",
    area_id: "pari-chowk",
    title: "Commercial Shop in Omaxe Connaught Place",
    slug: "shop-omaxe-connaught-place-pari-chowk",
    description: "Prime commercial shop in Omaxe Connaught Place near Pari Chowk, Greater Noida. High footfall area. Ground floor, road facing. Currently rented at 35K/month.",
    property_type: "shop",
    transaction_type: "sell",
    status: "active",
    price: 8500000,
    price_per_sqft: 17000,
    area_sqft: 500,
    bedrooms: null,
    bathrooms: 1,
    floor_number: 0,
    total_floors: 3,
    facing: "Road Facing",
    year_built: 2015,
    rera_id: null,
    is_featured: true,
    latitude: 28.4700,
    longitude: 77.5000,
    address: "Omaxe Connaught Place, Pari Chowk, Greater Noida",
    amenities: ["Power Backup", "Security", "Parking", "Elevator"],
    ai_analysis: null,
    nearby_places: null,
    view_count: 156,
    inquiry_count: 9,
    possession_date: "2015-01-01",
    created_at: "2024-04-20T00:00:00Z",
    updated_at: "2024-04-20T00:00:00Z",
    city: { id: "noida", name: "Greater Noida", slug: "noida", state: "Uttar Pradesh", description: null, latitude: 28.4700, longitude: 77.5000, meta: null, created_at: "" },
    area: { id: "pari-chowk", city_id: "noida", name: "Pari Chowk", slug: "pari-chowk", latitude: 28.4700, longitude: 77.5000, description: null, meta: null, created_at: "" },
    images: demoImages("p4", [401]),
  },
  {
    id: "p5",
    city_id: "noida",
    area_id: "sector-16c",
    title: "3BHK in Mahagun Mywoods",
    slug: "3bhk-mahagun-mywoods-sector-16c",
    description: "Affordable 3BHK in Mahagun Mywoods Phase 2. Well-maintained society with all amenities. Near schools and hospital.",
    property_type: "flat",
    transaction_type: "sell",
    status: "active",
    price: 5200000,
    price_per_sqft: 4300,
    area_sqft: 1210,
    bedrooms: 3,
    bathrooms: 2,
    floor_number: 9,
    total_floors: 20,
    facing: "West",
    year_built: 2018,
    rera_id: "UPRERAPRJ3456",
    is_featured: false,
    latitude: 28.5950,
    longitude: 77.4400,
    address: "Mahagun Mywoods, Sector 16C, Greater Noida West",
    amenities: ["Gym", "Park", "Power Backup", "Security", "Parking", "Children Play Area"],
    ai_analysis: null,
    nearby_places: null,
    view_count: 98,
    inquiry_count: 7,
    possession_date: "2018-09-01",
    created_at: "2024-05-15T00:00:00Z",
    updated_at: "2024-05-15T00:00:00Z",
    city: { id: "noida", name: "Greater Noida West", slug: "noida", state: "Uttar Pradesh", description: null, latitude: 28.5950, longitude: 77.4400, meta: null, created_at: "" },
    area: { id: "sector-16c", city_id: "noida", name: "Sector 16C", slug: "sector-16c", latitude: 28.5950, longitude: 77.4400, description: null, meta: null, created_at: "" },
    images: demoImages("p5", [501]),
  },
  {
    id: "p6",
    city_id: "noida",
    area_id: "sector-144",
    title: "2BHK in Gulshan Botnia",
    slug: "2bhk-gulshan-botnia-sector-144",
    description: "Compact 2BHK in Gulshan Botnia. Well-ventilated, north-facing. Society with good maintenance. Budget-friendly investment option.",
    property_type: "flat",
    transaction_type: "sell",
    status: "active",
    price: 3500000,
    price_per_sqft: 3890,
    area_sqft: 900,
    bedrooms: 2,
    bathrooms: 1,
    floor_number: 5,
    total_floors: 14,
    facing: "North",
    year_built: 2016,
    rera_id: "UPRERAPRJ7890",
    is_featured: false,
    latitude: 28.5800,
    longitude: 77.4350,
    address: "Gulshan Botnia, Sector 144, Greater Noida West",
    amenities: ["Park", "Power Backup", "Security", "Parking"],
    ai_analysis: null,
    nearby_places: null,
    view_count: 67,
    inquiry_count: 4,
    possession_date: "2016-06-01",
    created_at: "2024-06-01T00:00:00Z",
    updated_at: "2024-06-01T00:00:00Z",
    city: { id: "noida", name: "Greater Noida West", slug: "noida", state: "Uttar Pradesh", description: null, latitude: 28.5800, longitude: 77.4350, meta: null, created_at: "" },
    area: { id: "sector-144", city_id: "noida", name: "Sector 144", slug: "sector-144", latitude: 28.5800, longitude: 77.4350, description: null, meta: null, created_at: "" },
    images: demoImages("p6", [601]),
  },
  // Dholera properties
  {
    id: "d1",
    city_id: "dholera",
    area_id: "dholera-sir",
    title: "Residential Plot near Dholera Airport",
    slug: "plot-dholera-sir-airport-zone",
    description: "200 sq yard residential plot in Dholera SIR near the upcoming international airport. NA/NOC clear. Road-facing plot in a planned township.",
    property_type: "plot",
    transaction_type: "sell",
    status: "active",
    price: 1800000,
    price_per_sqft: 1000,
    area_sqft: 1800,
    bedrooms: null,
    bathrooms: null,
    floor_number: null,
    total_floors: null,
    facing: "East",
    year_built: null,
    rera_id: null,
    is_featured: true,
    latitude: 22.2400,
    longitude: 72.1900,
    address: "Near Airport Zone, Dholera SIR, Gujarat",
    amenities: ["Road Connectivity", "Electricity", "Water", "Boundary Wall"],
    ai_analysis: null,
    nearby_places: null,
    view_count: 342,
    inquiry_count: 28,
    possession_date: null,
    created_at: "2024-07-10T00:00:00Z",
    updated_at: "2024-07-10T00:00:00Z",
    city: { id: "dholera", name: "Dholera", slug: "dholera", state: "Gujarat", description: null, latitude: 22.2400, longitude: 72.1900, meta: null, created_at: "" },
    area: { id: "dholera-sir", city_id: "dholera", name: "Dholera SIR", slug: "dholera-sir", latitude: 22.2400, longitude: 72.1900, description: null, meta: null, created_at: "" },
    images: demoImages("d1", [701]),
  },
  {
    id: "d2",
    city_id: "dholera",
    area_id: "tp-40",
    title: "Commercial Plot in TP-40, Dholera",
    slug: "commercial-plot-tp40-dholera",
    description: "Commercial plot in TP-40 zone of Dholera SIR. Ideal for warehouse, office, or mixed-use development. Close to upcoming expressway.",
    property_type: "plot",
    transaction_type: "sell",
    status: "active",
    price: 3200000,
    price_per_sqft: 800,
    area_sqft: 4000,
    bedrooms: null,
    bathrooms: null,
    floor_number: null,
    total_floors: null,
    facing: "Road Facing",
    year_built: null,
    rera_id: null,
    is_featured: false,
    latitude: 22.2500,
    longitude: 72.2000,
    address: "TP-40, Dholera SIR, Gujarat",
    amenities: ["Road Connectivity", "Electricity", "Water"],
    ai_analysis: null,
    nearby_places: null,
    view_count: 128,
    inquiry_count: 8,
    possession_date: null,
    created_at: "2024-08-05T00:00:00Z",
    updated_at: "2024-08-05T00:00:00Z",
    city: { id: "dholera", name: "Dholera", slug: "dholera", state: "Gujarat", description: null, latitude: 22.2500, longitude: 72.2000, meta: null, created_at: "" },
    area: { id: "tp-40", city_id: "dholera", name: "TP-40", slug: "tp-40", latitude: 22.2500, longitude: 72.2000, description: null, meta: null, created_at: "" },
    images: demoImages("d2", [801]),
  },
  {
    id: "d3",
    city_id: "dholera",
    area_id: "tp-41",
    title: "Investment Plot in TP-41, Dholera SIR",
    slug: "investment-plot-tp41-dholera",
    description: "150 sq yard residential plot in TP-41. Government-approved layout with clear documentation. Excellent long-term investment opportunity in India's first smart city.",
    property_type: "plot",
    transaction_type: "sell",
    status: "active",
    price: 1200000,
    price_per_sqft: 890,
    area_sqft: 1350,
    bedrooms: null,
    bathrooms: null,
    floor_number: null,
    total_floors: null,
    facing: "North",
    year_built: null,
    rera_id: null,
    is_featured: false,
    latitude: 22.2600,
    longitude: 72.2100,
    address: "TP-41, Dholera SIR, Gujarat",
    amenities: ["Road Connectivity", "Electricity", "Water", "Garden"],
    ai_analysis: null,
    nearby_places: null,
    view_count: 203,
    inquiry_count: 15,
    possession_date: null,
    created_at: "2024-09-01T00:00:00Z",
    updated_at: "2024-09-01T00:00:00Z",
    city: { id: "dholera", name: "Dholera", slug: "dholera", state: "Gujarat", description: null, latitude: 22.2600, longitude: 72.2100, meta: null, created_at: "" },
    area: { id: "tp-41", city_id: "dholera", name: "TP-41", slug: "tp-41", latitude: 22.2600, longitude: 72.2100, description: null, meta: null, created_at: "" },
    images: demoImages("d3", [901]),
  },
];

export function getPropertiesByCity(citySlug: string) {
  return sampleProperties.filter((p) => p.city_id === citySlug);
}

export function getFeaturedProperties() {
  return sampleProperties.filter((p) => p.is_featured);
}

export function getPropertyBySlug(slug: string) {
  return sampleProperties.find((p) => p.slug === slug);
}
